"""new columns for store and user tables

Revision ID: 6b5c0c7e9179
Revises: 85bdf0f039e1
Create Date: 2024-08-10 00:44:41.491077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b5c0c7e9179'
down_revision: Union[str, None] = '85bdf0f039e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('stores', sa.Column('last_active', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'last_active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_active',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('stores', 'last_active')
    op.drop_column('stores', 'created_at')
    # ### end Alembic commands ###
