"""changed advertisments table

Revision ID: b8003b95e609
Revises: e471fb36e294
Create Date: 2024-09-09 09:11:41.091510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8003b95e609'
down_revision: Union[str, None] = 'e471fb36e294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'picture')
    # ### end Alembic commands ###
