"""changed advertisments table

Revision ID: e471fb36e294
Revises: 69e37988dff8
Create Date: 2024-09-09 08:47:56.865147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e471fb36e294'
down_revision: Union[str, None] = '69e37988dff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('advertisements', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('advertisements', sa.Column('timer', sa.Integer(), nullable=True))
    op.add_column('advertisements', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('advertisements', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.drop_constraint('advertisements_service_fkey', 'advertisements', type_='foreignkey')
    op.drop_constraint('advertisements_payment_methode_fkey', 'advertisements', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements', 'payment_methodes', ['payment_method_id'], ['id'])
    op.create_foreign_key(None, 'advertisements', 'services', ['service_id'], ['id'])
    op.drop_column('advertisements', 'service')
    op.drop_column('advertisements', 'payment_methode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('payment_methode', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('advertisements', sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.drop_constraint(None, 'advertisements', type_='foreignkey')
    op.create_foreign_key('advertisements_payment_methode_fkey', 'advertisements', 'payment_methodes', ['payment_methode'], ['id'])
    op.create_foreign_key('advertisements_service_fkey', 'advertisements', 'services', ['service'], ['id'])
    op.drop_column('advertisements', 'payment_method_id')
    op.drop_column('advertisements', 'service_id')
    op.drop_column('advertisements', 'timer')
    op.drop_column('advertisements', 'is_active')
    op.drop_column('advertisements', 'owner_id')
    # ### end Alembic commands ###
