"""debug

Revision ID: 18133aca5268
Revises: 3e6612839302
Create Date: 2024-09-11 19:29:35.063891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18133aca5268'
down_revision: Union[str, None] = '3e6612839302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_service_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'services_categories', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_service_id_fkey', 'services', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
