"""new columns for store and user tables

Revision ID: 1dc954877ad2
Revises: 6b5c0c7e9179
Create Date: 2024-08-10 00:53:12.499519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc954877ad2'
down_revision: Union[str, None] = '6b5c0c7e9179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('store_main_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'store_main_picture')
    # ### end Alembic commands ###
