"""Changed models and tables advertisements to services and services to services_categories

Revision ID: 3e6612839302
Revises: 6c4fa247a961
Create Date: 2024-09-10 11:40:08.338097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6612839302'
down_revision: Union[str, None] = '6c4fa247a961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services_work_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('is_morning', sa.Boolean(), nullable=True),
    sa.Column('is_day', sa.Boolean(), nullable=True),
    sa.Column('is_evening', sa.Boolean(), nullable=True),
    sa.Column('time_in_second', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('advertisements_views')
    op.drop_table('advertisements_work_times')
    op.drop_table('advertisements')
    op.drop_table('advertisements_ratings')
    op.add_column('booked_services_table', sa.Column('service_id', sa.Integer(), nullable=False))
    op.drop_column('booked_services_table', 'advertisement_id')
    op.add_column('services', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('services', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('services', sa.Column('lon', sa.Float(), nullable=False))
    op.add_column('services', sa.Column('rating_count', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('views_count', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('services', sa.Column('date', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('is_store', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('payment_method_id', sa.Integer(), nullable=True))
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=3000),
               existing_nullable=True)
    op.create_foreign_key(None, 'services', 'payment_methodes', ['payment_method_id'], ['id'])
    op.create_foreign_key(None, 'services', 'services', ['service_id'], ['id'])
    op.drop_column('services', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.alter_column('services', 'description',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('services', 'payment_method_id')
    op.drop_column('services', 'service_id')
    op.drop_column('services', 'is_store')
    op.drop_column('services', 'email')
    op.drop_column('services', 'phone_number')
    op.drop_column('services', 'date')
    op.drop_column('services', 'is_active')
    op.drop_column('services', 'owner_id')
    op.drop_column('services', 'price')
    op.drop_column('services', 'views_count')
    op.drop_column('services', 'rating_count')
    op.drop_column('services', 'lon')
    op.drop_column('services', 'lat')
    op.drop_column('services', 'name')
    op.add_column('booked_services_table', sa.Column('advertisement_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('booked_services_table', 'service_id')
    op.create_table('advertisements_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('advertisement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rater_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='advertisements_ratings_pkey')
    )
    op.create_table('advertisements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=3000), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_method_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methodes.id'], name='advertisements_payment_method_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='advertisements_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='advertisements_pkey')
    )
    op.create_table('advertisements_work_times',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('advertisement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_morning', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_day', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_evening', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('time_in_second', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='advertisements_work_times_pkey')
    )
    op.create_table('advertisements_views',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('advertisement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rater_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='advertisements_views_pkey')
    )
    op.drop_table('services_work_times')
    op.drop_table('services_views')
    op.drop_table('services_ratings')
    op.drop_table('services_categories')
    # ### end Alembic commands ###
