"""Database creation_1

Revision ID: 6049ccfe7e41
Revises: 8a3f40e88998
Create Date: 2024-07-07 19:17:27.262659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6049ccfe7e41'
down_revision: Union[str, None] = '8a3f40e88998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
