"""Changed advertisement model

Revision ID: 6c4fa247a961
Revises: e114d62c517c
Create Date: 2024-09-09 19:08:37.204168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4fa247a961'
down_revision: Union[str, None] = 'e114d62c517c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements_work_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('is_morning', sa.Boolean(), nullable=True),
    sa.Column('is_day', sa.Boolean(), nullable=True),
    sa.Column('is_evening', sa.Boolean(), nullable=True),
    sa.Column('time_in_second', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_services_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=255), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('advertisements', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('advertisements', sa.Column('lon', sa.Float(), nullable=False))
    op.drop_column('advertisements', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('advertisements', 'lon')
    op.drop_column('advertisements', 'lat')
    op.drop_table('booked_services_table')
    op.drop_table('advertisements_work_times')
    # ### end Alembic commands ###
