"""Added new models for services

Revision ID: e114d62c517c
Revises: c27885ff9acf
Create Date: 2024-09-09 17:08:36.538510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e114d62c517c'
down_revision: Union[str, None] = 'c27885ff9acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('date', sa.String(length=255), nullable=True))
    op.add_column('advertisements', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.add_column('advertisements', sa.Column('email', sa.String(length=255), nullable=True))
    op.drop_column('advertisements', 'timer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('timer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('advertisements', 'email')
    op.drop_column('advertisements', 'phone_number')
    op.drop_column('advertisements', 'date')
    # ### end Alembic commands ###
